# neopo: A lightweight solution for local Particle development.
# Copyright (c) 2020 Nathan Robinson.

os:
  - linux
  - osx
language: shell
install:
  - source travis.sh
  - neopo install
script:
  - neopo help
  - neopo load travisTests
  - neopo script travisTests