name: Test neopo python package

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          source tests/travis.sh
          neopo install
    - name: Test neopo
      run: |
          neopo help
          neopo load tests/travisTests
          neopo script travisTests
          python tests/travis-neopo.py