name: python-pip

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          ./install.sh
          neopo help
          neopo particle
    - name: Test neopo (bash)
      run: |
          neopo load ci/travisTests
          neopo script travisTests
    # - name: Test (python)
    #   run: |
    #       python ci/github-neopo.py